
workdir: "/scratch/cgobet/270123_IE_GTEX_Adipose_Visceral/" # Working directory to be defined by user
homedir: "/home/cgobet/270123_IE_GTEX/snakemake/" # Home directory to be defined by user
ref: "/scratch/cgobet/270123_IE_GTEX_2/REF_2/" # RNA STAR / Kallisto REF PATH

samples: Adipose_Visceral.tsv # Subject ID to analyze
js: 'file-manifest.json' # default json list from GTEX

species: Human # Species to be defined by user 
#URL for Ensembls sequence files for Human
Human:
  gtf: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.basic.annotation.gtf.gz"
  genome: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/GRCh38.primary_assembly.genome.fa.gz"
  cDNA: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.pc_transcripts.fa.gz"

