Name: astafev_2024
Species: mm10
Promoterome: '/home/jbreda/Promoterome/resources/mm10/promoterome_blacklist_annotation.gff'
GenomeFiles:
    - genome.fa
    - gene_annotation.gtf
    - cdna.fa
URLs:
    gtf:    "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M23/gencode.vM23.primary_assembly.annotation.gtf.gz"
    genome: "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M23/GRCm38.primary_assembly.genome.fa.gz"
    cDNA:   "ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M23/gencode.vM23.pc_transcripts.fa.gz"